### ISSUE TITLE
misleading statement in recent article

### ISSUE THREAD

**Issue by conradsnicta** [RcppCore/RcppArmadillo#184] opened 2017-10-26 02:46 UTC
@eddelbuettel @coatless - I came across your recent article titled "Extending R with C++: A Brief Introduction to Rcpp".  In the "Fast linear model fits" subsection pertaining to RcppArmadillo (page 21 of the accepted manuscript), there is a curious foonote (5) about the solver (LAPACK vs LINPACK), which looks misleading.

The footnote implies that the solver in LAPACK is somehow "inferior" to the LINPACK based solver. This is not right. It's not simply a matter of LAPACK vs LINPACK, as LAPACK itself has a bazillion ways to solve linear systems.

Up to Armadillo 6.200, a "simple" fast solver was used.  However, since Armadillo 6.300, a considerably more elaborate mechanism is used to obtain notably **more robust** solutions. The solver uses **iterative refinement** to improve the quality of solutions. Furthermore, if no exact solution can be found, then an approximate solution is attempted instead of simply failing. The user can choose to fallback to using the "simple" solver using the `solve_opts::fast` option to [solve()](http://arma.sourceforge.net/docs.html#solve).

I would recommend to alter or remove the misleading footnote from your pre-print version of the recent article, as well as any future publications. The statement in the footnote is at best misleading, and at worst incorrect. The implied message in the statement (ie. robustness of solutions) perhaps applied to Armadillo versions 6.200 and earlier, which is ancient history at this point. However, there is considerable doubt whether the statement in the footnote still applies: the solver has been considerably improved in Armadillo 6.300. We are now up to Armadillo 8.200, meaning pretty much everybody is using the improved solve() function.

**Comment by eddelbuettel** [comment] 2017-10-26 03:15
@conradsnicta I believe we may have been over this a few years ago.  The discussion in the footnote is mostly about the contrast to R, which ships a _modified_ LINPACK routine in order to deal better with ill-conditioned matrices--and the footnote tells you why.  This is a standard approach in (advanced) computational statistics and where is differs from numerical analysis (and most numerical algorithms people almost never "get" this).   

Now, years ago, I tried to actually cook up an example that does exhibit this. It is actually pretty hard as double precision is pretty good.  At the time, @dmbates helped out with the example we still have in RcppEigen's `fastLm()` routine.   (Do `library(RcppEigen); example(fastLm)` to run it. It is also included below.) 

Running it in RcppArmadillo yields "bad" results using the `solve()` we use there:

```r
R> library(RcppArmadillo)
R> dd <- data.frame(f1 = gl(4, 6, labels = LETTERS[1:4]), f2 = gl(3, 2, labels = letters[1:3]))[-(7:8), ]
R> xtabs(~ f2 + f1, dd)
   f1
f2  A B C D
  a 2 0 2 2
  b 2 2 2 2
  c 2 2 2 2
R> mm <- model.matrix(~ f1 * f2, dd)
R> kappa(mm) 
[1] Inf
R> set.seed(1)
R> dd$y <- mm %*% seq_len(ncol(mm)) + rnorm(nrow(mm), sd = 0.1)
R> summary(fastLm(y ~ f1 * f2, dd))

Call:
fastLm.formula(formula = y ~ f1 * f2, data = dd)

Residuals:
       Min.     1st Qu.      Median     3rd Qu.        Max. 
-1.2155e-01 -4.7016e-02 -1.4211e-14  4.7016e-02  1.2155e-01 

            Estimate   StdErr t.value  p.value    
(Intercept)  0.97786  0.06100   16.03 1.84e-08 ***
f1B          7.02046  0.04067  172.62  < 2e-16 ***
f1C          3.11722  0.08627   36.13 6.27e-12 ***
f1D          4.06852  0.08627   47.16 4.43e-13 ***
f2b          5.06012  0.08627   58.65 5.04e-14 ***
f2c          5.99759  0.08627   69.52 9.25e-15 ***
f1B:f2b      2.00285  0.06430   31.15 2.73e-11 ***
f1C:f2b      7.70300  0.12201   63.13 2.42e-14 ***
f1D:f2b      8.96425  0.12201   73.47 5.32e-15 ***
f1B:f2c      5.01761  0.06430   78.03 2.92e-15 ***
f1C:f2c     10.96133  0.12201   89.84 7.14e-16 ***
f1D:f2c     12.04108  0.12201   98.69 2.79e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.0863 on 10 degrees of freedom
Multiple R-squared:    1,	Adjusted R-squared:    1
R> 
```

That just redid the RcppEigen example step by step.  Whereas in the RcppEigen case (with standard `lm()` as a comparison) it works as well (due to @dmbates having selected an appropriate pivoting solution) and _removes one coefficient to reflect the missing rank_.  

```r
fastLmR>   ## standard R interface for formula or data returning object of class fastLm
fastLmR>   flmmod <- fastLm( log(Volume) ~ log(Girth), data=trees)

fastLmR>   summary(flmmod)

Call:
fastLm.formula(formula = log(Volume) ~ log(Girth), data = trees)

Residuals:
    Min.  1st Qu.   Median  3rd Qu.     Max. 
-0.20600 -0.06870  0.00101  0.07260  0.24800 

            Estimate Std. Error t value Pr(>|t|)    
(Intercept) -2.35332    0.23066  -10.20 4.18e-11 ***
log(Girth)   2.19997    0.08983   24.49  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.115 on 29 degrees of freedom
Multiple R-squared: 0.954,	Adjusted R-squared: 0.952

fastLmR>   ## case where non-rank-revealing methods break down
fastLmR>   dd <- data.frame(f1 = gl(4, 6, labels = LETTERS[1:4]),
fastLm+                    f2 = gl(3, 2, labels = letters[1:3]))[-(7:8), ]

fastLmR>   xtabs(~ f2 + f1, dd)     # one missing cell
   f1
f2  A B C D
  a 2 0 2 2
  b 2 2 2 2
  c 2 2 2 2

fastLmR>   mm <- model.matrix(~ f1 * f2, dd)

fastLmR>   kappa(mm)                # large, indicating rank deficiency
[1] Inf

fastLmR>   set.seed(1)

fastLmR>   dd$y <- mm %*% seq_len(ncol(mm)) + rnorm(nrow(mm), sd = 0.1)

fastLmR>   summary(lm(y ~ f1 * f2, dd))     # detects rank deficiency

Call:
lm(formula = y ~ f1 * f2, data = dd)

Residuals:
   Min     1Q Median     3Q    Max 
-0.122 -0.047  0.000  0.047  0.122 

Coefficients: (1 not defined because of singularities)
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   0.9779     0.0582    16.8  3.4e-09 ***
f1B          12.0381     0.0823   146.3  < 2e-16 ***
f1C           3.1172     0.0823    37.9  5.2e-13 ***
f1D           4.0685     0.0823    49.5  2.8e-14 ***
f2b           5.0601     0.0823    61.5  2.6e-15 ***
f2c           5.9976     0.0823    72.9  4.0e-16 ***
f1B:f2b      -3.0148     0.1163   -25.9  3.3e-11 ***
f1C:f2b       7.7030     0.1163    66.2  1.2e-15 ***
f1D:f2b       8.9643     0.1163    77.1  < 2e-16 ***
f1B:f2c           NA         NA      NA       NA    
f1C:f2c      10.9613     0.1163    94.2  < 2e-16 ***
f1D:f2c      12.0411     0.1163   103.5  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.0823 on 11 degrees of freedom
Multiple R-squared:     1,	Adjusted R-squared:     1 
F-statistic: 1.86e+04 on 10 and 11 DF,  p-value: <2e-16


fastLmR>   try(summary(fastLm(y ~ f1 * f2, dd))) # also detects rank deficiency

Call:
fastLm.formula(formula = y ~ f1 * f2, data = dd)

Residuals:
   Min. 1st Qu.  Median 3rd Qu.    Max. 
 -0.122  -0.047   0.000   0.047   0.122 

            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.97786    0.05816   16.81 3.41e-09 ***
f1B         12.03807    0.08226  146.35  < 2e-16 ***
f1C          3.11722    0.08226   37.90 5.22e-13 ***
f1D          4.06852    0.08226   49.46 2.83e-14 ***
f2b          5.06012    0.08226   61.52 2.59e-15 ***
f2c          5.99759    0.08226   72.91 4.01e-16 ***
f1B:f2b     -3.01476    0.11633  -25.92 3.27e-11 ***
f1C:f2b      7.70300    0.11633   66.22 1.16e-15 ***
f1D:f2b      8.96425    0.11633   77.06  < 2e-16 ***
f1B:f2c           NA         NA      NA       NA    
f1C:f2c     10.96133    0.11633   94.23  < 2e-16 ***
f1D:f2c     12.04108    0.11633  103.51  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.0823 on 11 degrees of freedom
Multiple R-squared:    1,	Adjusted R-squared:    1
R> 
```

As you can see here both `lm()` (from R) and `fastLm()` (from RcppEigen) drop one coefficient.  Our `fastLm()` from RcppArmadillo does not.   As such the footnote, esoteric as it may be, should stand.

I would be all ears to hear how we can use the more robust solver you have.   Can this serve as a testbed?  We file this as extension topic.  But the footnote is not incorrect as you can see here, so I close this.

**Comment by eddelbuettel** [comment] 2017-10-26 03:16
By the way: same content as the PeerJ preprint but, more tightly typeset [here in the update Rcpp Intro vignette](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-introduction.pdf).

**Comment by eddelbuettel** [comment] 2017-10-26 03:19
Sorry: And meant to add that _in practice_ it does not seem to matter all that much either way.  I have yet to run into a not-explicitly-and-on-purpose-degenerate case where it mattered.  As such, I am not afraid to use `fastLm()` based on `arma::solve()`.

**Comment by conradsnicta** [comment] 2017-10-26 03:31
@eddelbuettel @coatless  If the matrix has a poor (large) condition number, equilibration can help. Example:

    arma::colvec coef = arma::solve(X, y, arma::solve_opts::equilibrate);

See the docs for [solve()](http://arma.sourceforge.net/docs.html#solve) for more details on the options.

**Comment by eddelbuettel** [comment] 2017-10-26 03:41
Getting late here -- but I just tried, changing `fastLm()` to do 

```c++
    arma::colvec coef = arma::solve(X, y,     // fit model y ~ X ...
                                    arma::solve_opts::equilibrate); 
```

but no effect yet.  Tomorrow, with more coffee, I'll peruse the solve docs.

**Comment by coatless** [comment] 2017-10-26 04:51
@conradsnicta thanks for bringing this up! First, the strides _Armadillo_ has taken to establish robust estimation is greatly appreciated.

When we were writing that paper, circa 2016, I remember wanting to emphasize results between `fastLM` and `lm` in _R_ differed depending on any rank deficiencies that arose. This was the result of an experience I had when implementing a low-level variant of `lm` with _Armadillo_'s `solve` to provide an initial calibration values for a grid search. The footnote "evolved" after a few reviewers suggested additional changes.

However, the crux of the issue is still accurate. Prof. Ben Bolker (@bbolker) explained this very eloquently when responding to ["Why does `fastLm()` return results when I run a regression with one observation?"](https://stackoverflow.com/a/37657606/1345455)

If you look at the `?fastLM` function documentation, which is a bit outdated but conveys the important point of how _R_'s `lm` function is structured: 

> The reason that Armadillo can do something like lm.fit faster than the functions in the stats package is because Armadillo uses the Lapack version of the QR decomposition while the stats package uses a modified Linpack version. Hence Armadillo uses level-3 BLAS code whereas the stats package uses level-1 BLAS. However, Armadillo will either fail or, worse, produce completely incorrect answers on rank-deficient model matrices whereas the functions from the stats package will handle them properly due to the modified Linpack code.

Unfortunately, this isn't quite true anymore. As you rightly pointed out, Armadillo now attempts to use LU-decomposition with iterative refinement (LUIR) whenever possible with a fall back to QR decomposition under the `solve_approx_fast` or SVD. 

https://github.com/RcppCore/RcppArmadillo/blob/6bb3979d6ee9f7fa822ad5c482e3f848e7a6c42e/inst/include/armadillo_bits/auxlib_meat.hpp#L3036-L3408

Moreover, the issue with these rank deficient matrices that are being computed is the dimensionality mismatch, e.g. non-square matrices. If we did attempt to limit with `arma::solve_opts::equilibrate`,  we would subsequently receive the warning: 

> solve(): option 'equilibrate' ignored for non-square matrix

As a consequence of supplying this flag, we are inadvertently triggering the evaluation to move from a QR decomposition to using SVD, per:

https://github.com/RcppCore/RcppArmadillo/blob/6bb3979d6ee9f7fa822ad5c482e3f848e7a6c42e/inst/include/armadillo_bits/glue_solve_meat.hpp#L103-L124

**Comment by eddelbuettel** [comment] 2017-10-26 10:51
Confirmed that I also get the  `solve(): option 'equilibrate' ignored for non-square matrix` warning. So for
fitting linear regression models where n is usually much larger than k, we may not benefit from the improved code in Armadillo.

**Closed by eddelbuettel** 2017-10-26 10:51 UTC

**Comment by eddelbuettel** [comment] 2017-10-26 11:03
Constructive pull requests for either piece of the documentation are always welcome; it is all in this repo.
