### ISSUE TITLE
Compiler/openMP issue on Ubuntu 17.04

### ISSUE THREAD

**Issue by AVSuni** [RcppCore/RcppArmadillo#180] opened 2017-10-18 15:31 UTC
I am trying to install R packages on Ubuntu 17.04. For every package with dependencies with RcppArmadillo (0.8.100.1.0), I get: 

'WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+'. 

I use GCC (6) and Clang (3.8) as compilers. Both should support OpenMP 3.0+. Is this error message for real? 

I have read about other people's similar problems, but they seem to be associated with OSX. Many thanks.

**Comment by eddelbuettel** [comment] 2017-10-18 16:46
It is a _warning_ and you can overcome it by adding `-fopenmp` to your compiler and linker flags.

The easiest _quick_ solution is to do so in `~/.R/Makevars`.  The complete solution is to patch each package you are compiling.   RcppArmadillo cannot pass parameters to it.

Other possibilities are to downgrade RcppArmadillo so that OpenMP is not on by default, or to override the compilation default in its header, or via a compiler switch.   That would depart from upstream which is why we don't do it.

I suggest to close this as it is not a bug in the package.  It is a feature.  OpenMP is used, and it simply tells you that you could have it, but don't.

**Comment by AVSuni** [comment] 2017-10-19 13:54
Thank you, Dirk. I will add `-fopenmp` to my `~/.R/Makevars`. However, I didn't quite understand how "it is not a bug in the package. It is a feature. OpenMP is used, and it simply tells you that you could have it, but don't." I may have misunderstood something about my system, but I thought it is fully capable of openMP. Admittedly, much of this is new to me. Thanks again for your help.

**Comment by eddelbuettel** [comment] 2017-10-19 14:13
>  I thought it is fully capable of openMP. 

Indeed, and that is a good thing.  But it _needs to actually turn it on_ which adding `-fopenmp` does.

The by-default setup is crappy now, but we (ie Rcpp, RcppArmadillo) can't do much.  [Here is what one package did](https://stackoverflow.com/questions/46723854/rcpparmadillo-using-autoconf-to-disable-openmp) following what RcppArmadillo does for its own build.

**Comment by AVSuni** [comment] 2017-10-19 15:34
Thank you. I see what you mean. Once I edit `~/.R/Makevars`, I can reinstall all packages via install.views() and they will automatically recognise openMP support, correct? Many thanks.

**Comment by eddelbuettel** [comment] 2017-10-19 17:31
Correct.  You can also edit `/etc/R/Makeconf` to get others users on your system, but that file changes on upgrades.  Your local one is just yours.

**Comment by AVSuni** [comment] 2017-10-19 18:00
Awesome, thank you.

**Comment by conradsnicta** [comment] 2017-10-20 03:33
@eddelbuettel - This doesn't look right. The warning message given by Armadillo should only be printed if two following two conditions are both met: (1) the user has **enabled** OpenMP, and (2) the compiler's implementation of OpenMP is too old.  See line 455 in the current implementation of `include/armadillo_bits/compiler_setup.hpp` https://github.com/conradsnicta/armadillo-code/blob/unstable/include/armadillo_bits/compiler_setup.hpp#L455

Maybe there is something not quite right in the RcppArmadillo setup?  For example, is ARMA_USE_OPENMP forcefully enabled anywhere?  If so, I recommend removing that.

Armadillo will automatically use OpenMP if the user has specified the `-fopenmp` compiler switch. There is no need to do anything else.  The use of OpenMP is recommended with Armadillo, but **not required**.

**Comment by eddelbuettel** [comment] 2017-10-20 10:54
It's complicated.  "We" can only do what R let's us do.  Because all compilations are via `R CMD ...`, ie `R CMD compile ...` (say, and behind the scenes) the R configuration matters.  

Which is examined when RcppArmadillo is installed, and recorded.  The test is essence studying whether R itself passes `-fopenmp` down or, and recording it.   (With a special exception for macOS, but that is another drama in itself.)

So if R has seen OpenMP, we use it in _RcppArmadillo_.  Now what is being talked about is that _client packages of RcppArmadillo_ trigger the warning, and that is mostly ... because they do (not) yet add `-fopenmp` themselves to _their_ builds.  So (Rcpp)Armadillo can have OpenMP, expects it and does not see it.  Hence the message.

Little we can do as we cannot / should not rewrite other people's `src/Makevars`.  The warning is, actually, the Right Thing (TM).

**Comment by eddelbuettel** [comment] 2017-10-20 11:38
Ok, will now append this to the header file where set/unset OpenMP use based on whether R has it or now:

```c++
// Many client packages do not set the OpenMP compiler flag in their src/Makevars
// (ie add $(SHLIB_OPENMP_CXXFLAGS) to the PKG_CXXFLAGS line as we do) so to tone
// down the line noise we ask Armadillo not to print the warning
#ifdef ARMA_USE_OPENMP
#define ARMA_DONT_PRINT_OPENMP_WARNING 1
#endif
```

Thanks for the suggestion @conradsnicta

**Comment by conradsnicta** [comment] 2017-10-20 12:20
@eddelbuettel - I suggest expanding the code to issue an RppArmadillo specific warning, in order to encourage people to modify the compiler flags in their packages.  Perhaps something along these lines:

    #ifdef ARMA_USE_OPENMP
      #if !defined(_OPENMP)
        #pragma message("NOTE: to enable OpenMP based speedups in Armadillo, add -fopenmp to compiler flags")
      #endif
      #define ARMA_DONT_PRINT_OPENMP_WARNING
    #endif

**Comment by eddelbuettel** [comment] 2017-10-20 14:59
I agree with this _in principle_ but in practice we end up generating ten lines of effing line noise for each and every compilation unit.    From (test-)compiling the small RcppArmadillo-using RcppSMC package using a as-of-now uncommitted edit to the same pragma logic to have more hints:

```sh
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/RcppArmadillo/include"    -fpic  -g -O3 -Wall -pipe -Wno-unused  -march=native -c pfnonlinbs.cpp -o pfnonlinbs.o
In file included from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloForward.h:28:0,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from ../inst/include/population.h:33,
                 from ../inst/include/sampler.h:36,
                 from ../inst/include/smctc.h:101,
                 from pfnonlinbs.cpp:29:
/usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloConfig.h:117:194: note: #pragma message: NOTE: To enable OpenMP-based speedups, add -fopenmp to the compiler flags. See Writing R Extension (Sec 1.2.1) and R Installation + Administration (Sec 6.3.3) for details.
     #pragma message("NOTE: To enable OpenMP-based speedups, add -fopenmp to the compiler flags. See Writing R Extension (Sec 1.2.1) and R Installation + Administration (Sec 6.3.3) for details.")
                                                                                                                                                                                                  
```

That would get repeated file by file.  I don't think I want to impose that on the world.

**Comment by eddelbuettel** [comment] 2017-10-29 12:20
If you install the GitHub-release version 0.8.200.1.1, this issue should be addressed. Do either

```r
drat::addRepo("RcppCore")             # RcppCore drat repo known for rest of session
install.packages("RcppArmadillo")
```

or 

```r
install.packages("RcppArmadillo", repos="https://RcppCore.github.io/drat")
```

**Closed by eddelbuettel** 2017-10-29 12:20 UTC
