### ISSUE TITLE
Does not compile on RHEL 6.5.7

### ISSUE THREAD

**Issue by rsjohnso** [RcppCore/RcppArmadillo#92] opened 2016-05-11 20:11 UTC
Downloaded from cran.r-project.org, I'm running on RHEL 6.5.7.  I have the following gcc RPM packages installed:

`compat-gcc-34-c++-3.4.6-19.el6.x86_64
compat-gcc-34-3.4.6-19.el6.x86_64
gcc-gfortran-4.4.7-4.el6.x86_64
libgcc-4.4.7-4.el6.x86_64
gcc-c++-4.4.7-4.el6.x86_64
libgcc-4.4.7-4.el6.i686
gcc-4.4.7-4.el6.x86_64`

When I attempt to install it I get the following output.

`sudo R CMD INSTALL  RcppArmadillo_0.6.700.6.0.tar.gz`

> * installing to library ‘/usr/lib64/R/library’
> * installing *source* package ‘RcppArmadillo’ ...
> ** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
> * checking LAPACK_LIBS: R-supplied partial LAPACK found
> * some operations may not be available
> ** libs
> g++ -m64 -I/usr/include/R -DNDEBUG  -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include"  -I../inst/include -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c RcppArmadillo.cpp -o RcppArmadillo.o
> In file included from ../inst/include/armadillo:107,
>                  from ../inst/include/RcppArmadilloForward.h:46,
>                  from ../inst/include/RcppArmadillo.h:31,
>                  from RcppArmadillo.cpp:22:
> ../inst/include/armadillo_bits/traits.hpp: In instantiation of ‘const bool arma::is_arma_type<std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum> >::value’:
> ../inst/include/armadillo_bits/op_logmat_meat.hpp:289:   instantiated from here
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem2’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem1’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_col’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_row’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_diagview’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtGlue’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtOp’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eGlue’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eOp’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Glue’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Op’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Gen’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Mat’
> ../inst/include/armadillo_bits/traits.hpp: In instantiation of ‘const bool arma::is_arma_type<std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum> >::value’:
> ../inst/include/armadillo_bits/op_logmat_meat.hpp:289:   instantiated from here
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem2’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem1’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_col’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_row’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_diagview’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtGlue’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtOp’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eGlue’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eOp’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Glue’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Op’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Gen’
> ../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
> ../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Mat’
> make: *** [RcppArmadillo.o] Error 1
> ERROR: compilation failed for package ‘RcppArmadillo’
> * removing ‘/usr/lib64/R/library/RcppArmadillo’

**Comment by kevinushey** [comment] 2016-05-11 20:46
Sounds like a dupe of https://github.com/RcppCore/RcppArmadillo/issues/85 -- you need a newer compiler.

**Comment by eddelbuettel** [comment] 2016-05-11 21:07
@kevinsushey is correct. 

I will add a note to `DESCRIPTION` and maybe even spill it out in SystemRequirements.

**Closed by eddelbuettel** 2016-05-11 21:07 UTC
