### ISSUE TITLE
RcppArmadilloConfig.h disabled ARMA_32BIT_WORD

### ISSUE THREAD

**Issue by githubtomtom** [RcppCore/RcppArmadillo#191] opened 2017-11-29 07:49 UTC
Hi,

The following line in RcppArmadilloConfig.h:
#define ARMA_32BIT_WORD 1

would deactivate ARMA_64BIT_WORD in Config.hpp, and reduce the maximum size of mat (or vec, or cube) to 0xffffffff, which is far too small for deep learning projects. We need to comment that line in order to increase the maximum size to 0xffffffffffffffff .

**Comment by coatless** [comment] 2017-11-29 09:14
So, the issue is you are not defining `ARMA_64BIT_WORD` in the `Makevars` file.

The line you are referencing here:

https://github.com/RcppCore/RcppArmadillo/blob/f20cc71ad6b1c730a79f2e5609733f741172b399/inst/include/RcppArmadilloConfig.h#L127-L129

Only triggers if `ARMA_64BIT_WORD` isn't defined.

I've written up this here: https://stackoverflow.com/a/40592237/1345455

**Comment by githubtomtom** [comment] 2017-11-29 10:55
Thanks, I responded in stackoverflow.

**Comment by eddelbuettel** [comment] 2017-11-29 12:33
> Thanks, I responded in stackoverflow.

Not well. I;d delete that question.

We have a slight problem as Armadillo's 64bit indexing is larger than R's which is why we didn't make this a default.  What @coatless suggested to you seems like the best bet.

**Comment by githubtomtom** [comment] 2017-11-29 12:39
Hi Dirk,

Actually I communicated with Conrad yesterday. He thinks it’s a “bug” and that’s him to ask me submitting a “bug report”...

I GUESS, it’s a better habit to modify RcppArmadilloConfig.h and config.hpp, rather than putting “#define xxx” in cpp.

What’s your opinion is this aspect?

Thanks,
M.Phil Computer Science,
Thomas

**Comment by coatless** [comment] 2017-11-29 16:15
@githubtomtom not sure why @conradsnicta would consider this a bug. As @eddelbuettel mentioned, _R_ cannot handle 64 bit indexing. Thus, you have to opt-in and typically pass back a smaller object.

c.f. discussion thread from December 2014

http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2014-December/008293.html

**Comment by eddelbuettel** [comment] 2017-11-29 17:07
And with that I think we can close this.  RcppArmadillo is a) for interacting with Armadillo from R so the default indexing makes sense and b) not preventing you from using 64bit integer indices internally.

**Closed by eddelbuettel** 2017-11-29 17:07 UTC
