### ISSUE TITLE
QR decomposition out of memory

### ISSUE THREAD

**Issue by cloudray8580** [RcppCore/RcppArmadillo#241] opened 2018-10-08 13:45 UTC
Hi, I'm new to mlpack. I'm trying to use linear regression to have a test on my .csv file. I'm using VS2017 for coding. The codes are shown below:
```
mat data;
bool loaded = mlpack::data::Load("C:/Users/Cloud/Desktop/LearnIndex/data/HilbertSortedPOIs2.csv", data);
arma::rowvec responses = data.row(data.n_rows - 1);
data.shed_row(data.n_rows - 1);
LinearRegression lr(data, responses);
```

Where the .csv file has about 1M rows and 6 columns. When I run the above codes, there is an error "error: arma::memory::acquire(): out of memory". I have a look into the call stack and find that the Q matrix in QR decomposition set its size to be (1M, 1M), which is definitely much larger than the size of my memory (16G). 

I'm wondering is there any way to run the LR with my dataset? Or I'm not using the right way for this?
Can anyone help me with this? Thanks.

I'm so sorry, I just relize that I post it to the wrong place, please ignore or close this issue. Sorry.

**Comment by eddelbuettel** [comment] 2018-10-08 14:07
Where is the `LinearRegression` class coming from, who wrote it, and why does it form an explicit `N x N`?

In short, every intermediate regression class should teach you to 
1. Not do this by hand
2. As a teaching exercise think HARD about the terms in (X'X)^{-1}.  Work out the dimension of that.

In everybody mulitplies to a temp object and inverts that.  Also see my `fastLm()` example _in the very sources and installation_ of RcppArmadillo.

This really is your conceptual issue, and not a bug so I am closing this.  In case you have an actual reproducible issue do of course feel free to reopen.

**Closed by eddelbuettel** 2018-10-08 14:07 UTC
